---
version: 2
models:
- name: "customers"
  columns:
  - name: "FIRST_NAME"
    dataType:
      type: "String"
  - name: "CUSTOMER_ID"
    dataType:
      type: "Number"
  - name: "LAST_NAME"
    dataType:
      type: "String"
  - name: "FIRST_ORDER"
    dataType:
      type: "Date"
  - name: "NUMBER_OF_ORDERS"
    dataType:
      type: "Number"
  - name: "MOST_RECENT_ORDER"
    dataType:
      type: "Date"
  tests: []
