name: HelloWorld_SQL
description: ''
version: '1.1'
author: null
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/test:
    name: test
    description: ''
    fabricUID: 119
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-07-10 23:40:53'
    author: alexahn@prophecy.io
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-06-03 21:32:25'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/stg_orders:
    name: stg_orders
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: order_id
        dataType:
          type: Integer
      - name: customer_id
        dataType:
          type: Integer
      - name: order_date
        dataType:
          type: Date
      - name: status
        dataType:
          type: String
    description: null
    author: alexahn@prophecy.io
    files:
    - models/staging/stg_orders.sql
    - .prophecy/ide/models/stg_orders.json
    - models/staging/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-06-03 21:34:10'
  .prophecy/metadata/sqlmodels/orders:
    name: orders
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: order_id
        dataType:
          type: Integer
      - name: customer_id
        dataType:
          type: Integer
      - name: order_date
        dataType:
          type: Date
      - name: status
        dataType:
          type: String
      - name: credit_card_amount
        dataType:
          type: Float
      - name: coupon_amount
        dataType:
          type: Float
      - name: bank_transfer_amount
        dataType:
          type: Float
      - name: gift_card_amount
        dataType:
          type: Float
      - name: amount
        dataType:
          type: Float
    description: This table has basic information about orders, as well as some derived
      facts based on payments
    author: alexahn@prophecy.io
    files:
    - models/orders.sql
    - .prophecy/ide/models/orders.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-06-03 21:34:10'
  .prophecy/metadata/sqlmodels/customers:
    name: customers
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: customer_id
        dataType:
          type: Integer
      - name: first_name
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
      - name: first_order
        dataType:
          type: Date
      - name: most_recent_order
        dataType:
          type: Date
      - name: number_of_orders
        dataType:
          type: Bigint
      - name: customer_lifetime_value
        dataType:
          type: Float
    description: This table has basic information about a customer, as well as some
      derived facts based on a customer's orders
    author: alexahn@prophecy.io
    files:
    - models/customers.sql
    - .prophecy/ide/models/customers.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-06-03 21:34:10'
  .prophecy/metadata/sqlmodels/stg_payments:
    name: stg_payments
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: payment_id
        dataType:
          type: Integer
      - name: order_id
        dataType:
          type: Integer
      - name: payment_method
        dataType:
          type: String
      - name: amount
        dataType:
          type: Float
    description: null
    author: alexahn@prophecy.io
    files:
    - models/staging/stg_payments.sql
    - .prophecy/ide/models/stg_payments.json
    - models/staging/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-06-03 21:34:10'
  .prophecy/metadata/sqlmodels/stg_customers:
    name: stg_customers
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: customer_id
        dataType:
          type: Integer
      - name: first_name
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
    description: null
    author: alexahn@prophecy.io
    files:
    - models/staging/stg_customers.sql
    - .prophecy/ide/models/stg_customers.json
    - models/staging/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-06-03 21:34:10'
sqlSnapshots: {}
sqlTests:
  .prophecy/metadata/sqltests/ref_int_orders_customers:
    name: ref_int_orders_customers
    description: null
    author: alexahn@prophecy.io
    files:
    - tests/ref_int_orders_customers.sql
    - .prophecy/ide/tests/data/singular/ref_int_orders_customers.json
    testType: SingularDataTest
    createdAt: '2024-06-04 19:12:59'
  .prophecy/metadata/sqltests/ref_int_orders_customers_2:
    name: ref_int_orders_customers_2
    description: null
    author: alexahn@prophecy.io
    files:
    - tests/ref_int_orders_customers_2.sql
    - .prophecy/ide/tests/data/singular/ref_int_orders_customers_2.json
    testType: SingularDataTest
    createdAt: '2024-06-04 21:33:36'
sqlMacros:
  .prophecy/metadata/sqlmacros/safe_add:
    name: safe_add
    macroType: expression
    description: A macro to safely add the fields specified in the field_list.
    author: alexahn@prophecy.io
    files:
    - macros/safe_add.sql
    - .prophecy/ide/macros/safe_add.json
    - macros/macros.yml
    createdAt: '2024-07-10 23:21:25'
  .prophecy/metadata/sqlmacros/test:
    name: test
    macroType: expression
    description: null
    author: alexahn@prophecy.io
    files:
    - macros/test.sql
    - .prophecy/ide/macros/test.json
    createdAt: '2024-07-30 00:43:55'
sqlSeeds:
  .prophecy/metadata/sqlseeds/raw_customers:
    name: raw_customers
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: id
        dataType:
          type: Integer
      - name: first_name
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
    description: null
    author: alexahn@prophecy.io
    files:
    - seeds/raw_customers.csv
    createdAt: '2024-06-03 21:34:10'
  .prophecy/metadata/sqlseeds/raw_orders:
    name: raw_orders
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: id
        dataType:
          type: Integer
      - name: user_id
        dataType:
          type: Integer
      - name: order_date
        dataType:
          type: Date
      - name: status
        dataType:
          type: String
    description: null
    author: alexahn@prophecy.io
    files:
    - seeds/raw_orders.csv
    createdAt: '2024-06-03 21:34:10'
  .prophecy/metadata/sqlseeds/raw_payments:
    name: raw_payments
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: id
        dataType:
          type: Integer
      - name: order_id
        dataType:
          type: Integer
      - name: payment_method
        dataType:
          type: String
      - name: amount
        dataType:
          type: Integer
    description: null
    author: alexahn@prophecy.io
    files:
    - seeds/raw_payments.csv
    createdAt: '2024-06-03 21:34:10'
sqlSources:
  .prophecy/metadata/sqlsources/test:
    name: test
    description: null
    author: alexahn@prophecy.io
    files:
    - models/test.yml
    createdAt: '2024-07-18 06:14:10'
    tables:
    - name: test
      schema: null
      description: null
      author: alexahn@prophecy.io
      createdAt: '2024-07-18 06:14:27'
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: alexahn@prophecy.io
  createdAt: '2024-06-03 21:32:25'
dependencies: []
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
